### ISSUE TITLE
Too slow on start

### ISSUE THREAD

**Issue by sabrimev** [thchia/react-oidc#23] opened 2019-12-16 11:28 UTC
It take roughly 10 seconds to redirect identity server login page. Am I doing something wrong?
When I check console log on start It calls the login page immediately but fails on server page then its being called again after 10 seconds. Here is the result from server page.

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.17.6</center>
</body>
</html>

**Comment by thchia** [comment] 2019-12-16 11:45
Hmm, so is it slow or not working (or both)? It sounds like it could the Identity Provider. Is there any way to get a reproduction?

**Comment by sabrimev** [comment] 2019-12-17 05:53
Actually its working but I think there is a problem when I initially start the app. I hit http://localhost:3000/ and it gives the error below on console, like 9-10 seconds later it redirects to identity server. But when I change my config to demo config of identity server (https://demo.identityserver.io/) its working properly. I get an instant redirect. What do you think it could be? An identity server problem or react-oidc ? Thanks for the fast reply btw :)

![image](https://user-images.githubusercontent.com/4224210/70968344-0514cd80-20aa-11ea-9049-08c8c6810fa7.png)

**Comment by sabrimev** [comment] 2019-12-17 06:33
> Hmm, so is it slow or not working (or both)? It sounds like it could the Identity Provider. Is there any way to get a reproduction?

**Comment by thchia** [comment] 2019-12-17 06:39
Based on what you’ve said it sounds like a server issue, especially since the issue goes away when you use the demo server.

Are you using a common Identity Provider like Google, or your own one?

Also, what is being requested in the console error you pasted. Could you share the network tab for that request too?

**Comment by sabrimev** [comment] 2019-12-17 07:45
I am using a private Identity provider which we own. Here is the screenshot of network tab;

![image](https://user-images.githubusercontent.com/4224210/70975004-1fef3e00-20ba-11ea-965a-aed1e1ab4d9b.png)

**Comment by thchia** [comment] 2019-12-23 08:30
So I’m fairly certain this looks like an issue with the Identity Provider but I can’t be 100% sure as I won’t be able to reproduce this with your custom provider.

Is there any further debugging you can do with the Identity Provider side?

And I assume the redirect routes are all setup correctly in your app too?

**Comment by sygnowskip** [comment] 2020-04-01 07:49
@thchia It's slow because it always starts with `signinSilent` which is incorrect in a situation where we're 100% sure that user won't log in before :)

Better implementation could be found here: https://github.com/AxaGuilDEv/react-oidc/blob/master/packages/core/src/services/oidcServices.js#L24

**Comment by thchia** [comment] 2020-04-01 11:22
Closed by #25

**Closed as completed by thchia** 2020-04-01 11:22 UTC
